-
  match: '^/eval(?:/(?<expr>.+))?$'
  body: |
    #{eval(context['expr'])}

-
  match: '(?:\.md|\.yml)$'
  status: 403
  body: forbidden

# Entry
-
  match: '^(?<uri>/(?<id>[\w\W\d]{4})/)(?:index.html)?$'
  handler: page.php
  view: entry.html
  cache: 'html/* content/*'

# Archive
-
  match: '^(?<uri>/archives(?:/(?<yyyymm>[1-9][0-9]{4}(?:[1][0-2]|[0][1-9]))/)?)(?:index.html)?$'
  handler: page.php
  view: index.html
  helper: Archive

# Top
-
  match: '^(?<uri>/)(?:index\.html)?$'
  handler: page.php
  view: index.html
  cache: 'html/* content/*'
  page: 1

# Paginated Index
-
  match: '^(?<uri>/page/(?<page>[\d]+)/)(?:index\.html)?$'
  handler: page.php
  view: index.html
  cache: 'html/* content/*'

# Directory
-
  match: '^(?<view>(?<uri>(/[^/]+)*/)(?:index\.html))$'
  handler: page.php
  cache: 'html/* content/*'
  condition: |
    File.exists?(File.join('html',context['view'].sub(/\.html$/,'.html.php')))

# css
-
 match: '^.+\.css$'
 handler: sass.sh
 content_type: text/css; charset=utf-8
 condition: |
   !`find html#{context['uri'].sub(/\.css$/, '.s[ac]ss')}`.empty?

# Xml
-
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+\.xml))$'
  content_type: application/xml; charset=utf-8
  handler: page.php
  cache: 'html/* content/*'
  condition: |
    File.exists?(File.join('html',context['view'].sub(/\.xml$/,'.xml.php')))

# Index
-
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+))$'
  handler: page.php
  cache: 'html/* content/*'
  condition: |
    File.exists?(File.join('html',context['view'].sub(/\.html$/,'.html.php')))
