- match: ^/env$
  body: |
    #{JSON.generate(env)}

- match: ^/context$
  body: |
    #{JSON.generate(context)}

- match: ^/query$
  body: |
    #{URI.decode_www_component(env['QUERY_STRING'])}

- match: ^/ruby$
  body: |
    #{"abc".sub(/c$/, 'd')}

- match: ^/cache_clear$
  body: |
    <pre>#{`rm -rfv /tmp/cms/*`}</pre>

-
  match: '\.md|\.yml'
  status: 403
  body: forbidden

# Entry
-
  match: '^(?<uri>/(?<id>[\w\W\d]{4})/)(?:index.html)?$'
  handler: page.php
  view: index.html
  main: entry.html
  helper: Entry
  cache: 'html/views/* content/*'

# Archive
-
  match: '^(?<uri>/archives(?:/(?<yyyymm>[1-9][0-9]{4}(?:[1][0-2]|[0][1-9]))/)?)(?:index.html)?$'
  handler: page.php
  view: index.html
  helper: Archive

# Top
-
  match: '^(?<uri>/)(?:index\.html)?$'
  handler: page.php
  view: index.html
  helper: Index
  cache: 'html/views/* content/*'
  page: 1

# Paginated Index
-
  match: '^(?<uri>/page/(?<page>[\d]+)/)(?:index\.html)?$'
  handler: page.php
  view: index.html
  helper: Index
  cache: 'html/views/* content/*'

# Directory
-
  match: '^(?<view>(?<uri>(/[^/]+)*/)(?:index\.html))$'
  handler: page.php
  helper: Page
  cache: 'html/views/* content/*'
  condition: |
    File.exists?('app/php/views',context['view']))

# css
-
 match: '^.+\.css$'
 handler: sass.sh
 content_type: text/css; charset=utf-8

# Xml
-
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+\.xml))$'
  content_type: application/xml; charset=utf-8
  handler: page.php
  helper: Page
  cache: 'html/views/* content/*'
  condition: |
    File.exists?(File.join('app/php/views',context['view']))

# Index
-
  match: '^(?<view>(?<uri>(/[^/]+)*/[^/]+))$'
  handler: page.php
  helper: Page
  cache: 'html/views/* content/*'
  condition: |
    File.exists?(File.join('app/php/views',context['view']))
